### ISSUE TITLE
MVC routes don't have custom annotations in attributes

### ISSUE THREAD

**Issue by tpoll** [jooby-project/jooby#3582]
On upgrading from `3.0.5` ->  `3.5.1`, we noticed that all of our custom annotations on mvc routes + mvc methods doesn't seem to work.

e.g. given an annotation like:

```java
@Target({ ElementType.METHOD, ElementType.TYPE, ElementType.ANNOTATION_TYPE })
@Retention(RetentionPolicy.RUNTIME)
public @interface MyTestAnnotation {
  String value() default "";
}
```

and a mvc route like 
```java
@MyTestAnnotation
public class TestResource {

  @Inject
  public TestResource() {
  }

  @GET("/hello")
  public String helloWorld(@QueryParam String property) {
    return "hello world" + "property"
  }
}
```
 
 `MyTestAnnotation` doesn't appear in `ctx.attributes` map. I've tested both at the class level and the resource level, and neither seem to work.
 
 The new generated code isn't setting any attributes, If I decompile the route class file from jooby 3.0.5, I can see the attribute properly being set.

**Comment by jknack** [comment]
It is bug, sorry. Did 3.0.5 set to empty string?

**Comment by tpoll** [comment]
Yeah, in 3.0.5 I see generated code like `var2.attribute("MyTestAnnotation", "");`

**Comment by jknack** [comment]
Todd, fixed in 3.5.3

**Comment by tpoll** [comment]
hey @jknack thanks for the quick changes! 

One small question here -- I'n my local testing of the update, calling ` ctx.getAttributes()` (for the `NettyContext`) in my Route.Filter still isn't returning the attributes like it did before.

I can see the attribute for the annotation on the `Route` object of the context, but the top level attributes don't contain those values.

Is this an expected regression?

**Comment by jknack** [comment]
never was: `ctx.getAttributes`, you are looking for: `ctx.getRoute().getAttributes()` right?

**Comment by tpoll** [comment]
Weird, 3.0.5 definitely has them in the `ctx.getAttributes`. I can switch the the route context if that isn't expected though.

**Comment by tpoll** [comment]
Ah, yeah you're right -- sorry about the confusion here.
